import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en' | 'ku';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  ar: {
    // Navigation
    home: 'الرئيسية',
    menu: 'القائمة',
    cart: 'السلة',
    // Homepage
    welcome: 'مرحباً بكم في',
    restaurantName: 'مندي الحطاب',
    subtitle: 'للأكلات الخليجية الشهية',
    orderNow: 'اطلب وتدلل',
    viewMenu: 'عرض القائمة',
    fastDelivery: 'توصيل سريع',
    freshIngredients: 'مكونات طازجة',
    authenticTaste: 'طعم أصيل',
    // Menu
    appetizers: 'المقبلات',
    mainCourses: 'الأطباق الرئيسية',
    desserts: 'الحلويات',
    beverages: 'المشروبات',
    addToCart: 'أضف للسلة',
    price: 'السعر',
    chickenDishes: 'أطباق الدجاج',
    meatDishes: 'أطباق اللحم',
    // Food items
    mandiChicken: 'مندي دجاج',
    mandiRibs: 'مندي ضلع',
    mandiShoulder: 'مندي كتف',
    mandiLamb: 'مندي لحم',
    halfChicken: 'نصف دجاجة مندي',
    qoziMeat: 'قوزي لحم',
    hanithChicken: 'حنيذ دجاج',
    hanithShoulder: 'كتف حنيذ',
    hanithMeat: 'حنيذ لحم',
    halfHanithChicken: 'نصف دجاجة حنيذ',
    pakistaniChicken: 'دجاج باكستاني',
    halfPakistaniChicken: 'نصف دجاجة باكستاني',
    mathabiChicken: 'دجاج مضبي',
    mathabiRib: 'ضلع مضبي',
    mathabiMeat: 'لحم مضبي',
    // Appetizers
    tabsi: 'تبسي',
    tabsiDesc: 'تبسي سوزار برژاو',
    fasoolia: 'فاصوليا',
    fasooliaDesc: 'فاصوليا لگڵ سوسی تامدار',
    soup: 'سوب',
    soupDesc: 'شوربة سوزار',
    jajik: 'جاجيک',
    jajikDesc: 'سەلاطەی ئارەم بە خێوار',
    sahawk: 'سحاوق',
    sahawkDesc: 'سەلاطەی تەماتە بە سیر',
    nuts: 'مكسرات',
    nutsDesc: 'مکسراتی هەمەجۆر',
    pickles: 'طرشي',
    picklesDesc: 'طرشي سوزار',
    yougurt: 'لبن',
    yougurtDesc: 'مەستی سادە',
    water: 'ماء',
    waterDesc: 'ئاوی بەتاڵکراو',
    'soft drinks': 'مشروبات غازية ',
    'soft drinksDesc': 'مشروبات غازية',
    halfMathabiChicken: 'نصف دجاجة مثابي',
    madfoonMeat: 'لحم مدفون',
    makboosMeat: 'لحم مكبوس',
    makboosChicken: 'دجاج مكبوس',
    halfMakboosChicken: 'نصف دجاجة مكبوس',
    qoziShoulder: 'كتف قوزي',
    mandiShoulderQozi: 'كتف مندي + قوزي',
    mandiShoulderQoziChicken: 'كتف مندي + قوزي + دجاج',
    mandiRibChicken: 'ضلع مندي + دجاج',
    mandiChickenShoulder: 'مندي دجاج + كتف',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChicken: 'نصف مندي دجاج + نصف مثابي دجاج + نصف مدفون دجاج',
    halfMandiChickenMandiMeat: 'نصف مندي دجاج + لحم مندي',
    extraRice: 'أرز إضافي',
    madfoonChicken: 'دجاج مدفون',
    appetizer1: 'مقبلات ١',
    appetizer2: 'مقبلات ٢',
    appetizer3: 'مقبلات ٣',
    // Descriptions
    mandiChickenDesc: 'دجاجة مندي + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    mandiRibsDesc: 'ضلع مندي (1 كيلو) + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    mandiShoulderDesc: 'كتف مندي (1 كيلو) + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    mandiLambDesc: 'مندي لحم (نصف كيلو) + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    halfChickenDesc: 'نصف دجاجة مندي + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    qoziMeatDesc: 'قوزي لحم (نصف كيلو) + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    hanithChickenDesc: 'دجاجة حنيذ + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    hanithShoulderDesc: 'كتف حنيذ (1 كيلو) + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    hanithMeatDesc: 'نصف كيلو حنيذ لحم + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    halfHanithChickenDesc: 'نصف دجاجة حنيذ + صينية زر مندي + فاصوليا + حاجيك + سحاوق + طرشي',
    pakistaniChickenDesc: 'دجاج باكستاني مع أرز وتوابل خاصة',
    halfPakistaniChickenDesc: 'نصف دجاجة باكستاني مع أرز وتوابل خاصة',
    mathabiChickenDesc: 'دجاج مضبي مشوي على الفحم مع أرز',
    mathabiRibDesc: 'ضلع لحم مضبي مع أرز',
    mathabiMeatDesc: 'لحم مضبي مع أرز',
    halfMathabiChickenDesc: 'نصف دجاجة مضبي مع أرز',
    madfoonMeatDesc: 'لحم مدفون مع أرز',
    makboosMeatDesc: 'لحم مكبوس مع أرز',
    makboosChickenDesc: 'دجاج مكبوس مع أرز',
    halfMakboosChickenDesc: 'نصف دجاجة مكبوس مع أرز',
    qoziShoulderDesc: 'كتف لحم قوزي مع أرز',
    mandiShoulderQoziDesc: 'كتف مندي مع قوزي وأرز',
    mandiShoulderQoziChickenDesc: 'كتف مندي مع قوزي ودجاج وأرز',
    mandiRibChickenDesc: 'ضلع مندي مع دجاج وأرز',
    mandiChickenShoulderDesc: 'مندي دجاج مع كتف وأرز',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChickenDesc: 'تشكيلة نصف دجاج مندي، مثابي، ومدفون مع أرز',
    halfMandiChickenMandiMeatDesc: 'نصف دجاج مندي مع لحم مندي وأرز',
    extraRiceDesc: 'صحن أرز إضافي',
    madfoonChickenDesc: 'دجاج مدفون مع أرز',
    appetizer1Desc: 'وصف مقبلات ١',
    appetizer2Desc: 'وصف مقبلات ٢',
    appetizer3Desc: 'وصف مقبلات ٣',
    // Cart
    yourOrder: 'طلبك',
    total: 'المجموع',
    checkout: 'إتمام الطلب',
    // Checkout
    customerInfo: 'معلومات العميل',
    name: 'الاسم',
    phone: 'رقم الهاتف',
    diningPreference: 'تفضيل الطعام',
    insideRestaurant: 'داخل المطعم',
    customLocation: 'موقع مخصص',
    branch: 'الفرع',
    branch1: 'فرع شارع كويه',
    branch2: 'فرع كراند ماجدي مول',
    tableNumber: 'رقم الطاولة',
    location: 'الموقع',
    submitOrder: 'إرسال الطلب',
    // Languages
    arabic: 'العربية',
    english: 'English',
    kurdish: 'کوردی'
  },
  en: {
    // Navigation
    home: 'Home',
    menu: 'Menu',
    cart: 'Cart',
    // Homepage
    welcome: 'Welcome to',
    restaurantName: 'Mandi Al-Hattab',
    subtitle: 'For Delicious Gulf Cuisine',
    orderNow: 'Order Now',
    viewMenu: 'View Menu',
    fastDelivery: 'Fast Delivery',
    freshIngredients: 'Fresh Ingredients',
    authenticTaste: 'Authentic Taste',
    // Menu
    appetizers: 'Appetizers',
    mainCourses: 'Main Courses',
    desserts: 'Desserts',
    beverages: 'Beverages',
    addToCart: 'Add to Cart',
    price: 'Price',
    chickenDishes: 'Chicken Dishes',
    meatDishes: 'Meat Dishes',
    // Food items
    mandiChicken: 'Mandi Chicken',
    mandiRibs: 'Mandi Ribs',
    mandiShoulder: 'Mandi Shoulder',
    mandiLamb: 'Mandi Lamb',
    halfChicken: 'Half Mandi Chicken',
    qoziMeat: 'Qozi Meat',
    hanithChicken: 'Hanith Chicken',
    hanithShoulder: 'Hanith Shoulder',
    hanithMeat: 'Hanith Meat',
    halfHanithChicken: 'Half Hanith Chicken',
    pakistaniChicken: 'Pakistani Chicken',
    halfPakistaniChicken: 'Half Pakistani Chicken',
    mathabiChicken: 'Mathabi Chicken',
    mathabiRib: 'Mathabi Rib',
    mathabiMeat: 'Mathabi Meat',
    halfMathabiChicken: 'Half Mathabi Chicken',
    madfoonMeat: 'Madfoon Meat',
    makboosMeat: 'Makboos Meat',
    makboosChicken: 'Makboos Chicken',
    halfMakboosChicken: 'Half Makboos Chicken',
    qoziShoulder: 'Qozi Shoulder',
    mandiShoulderQozi: 'Mandi Shoulder + Qozi',
    mandiShoulderQoziChicken: 'Mandi Shoulder + Qozi + Chicken',
    mandiRibChicken: 'Mandi Rib + Chicken',
    mandiChickenShoulder: 'Mandi Chicken + Shoulder',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChicken: 'Half Mandi Chicken + Half Mathabi Chicken + Half Madfoon Chicken',
    halfMandiChickenMandiMeat: 'Half Mandi Chicken + Mandi Meat',
    extraRice: 'Extra Rice',
    madfoonChicken: 'Madfoon Chicken',
    appetizer1: 'Appetizer 1',
    appetizer2: 'Appetizer 2',
    appetizer3: 'Appetizer 3',
    // Descriptions
    mandiChickenDesc: 'Mandi chicken + rice tray + beans + hajik + sahawiq + pickles',
    mandiRibsDesc: 'Mandi ribs (1 kg) + rice tray + beans + hajik + sahawiq + pickles',
    mandiShoulderDesc: 'Mandi shoulder (1 kg) + rice tray + beans + hajik + sahawiq + pickles',
    mandiLambDesc: 'Mandi lamb (0.5 kg) + rice tray + beans + hajik + sahawiq + pickles',
    halfChickenDesc: 'Half mandi chicken + rice tray + beans + hajik + sahawiq + pickles',
    qoziMeatDesc: 'Qozi meat (0.5 kg) + rice tray + beans + hajik + sahawiq + pickles',
    hanithChickenDesc: 'Hanith chicken + rice tray + beans + hajik + sahawiq + pickles',
    hanithShoulderDesc: 'Hanith shoulder (1 kg) + rice tray + beans + hajik + sahawiq + pickles',
    hanithMeatDesc: 'Half kilo hanith meat + rice tray + beans + hajik + sahawiq + pickles',
    halfHanithChickenDesc: 'Half hanith chicken + rice tray + beans + hajik + sahawiq + pickles',
    pakistaniChickenDesc: 'Pakistani chicken with rice and special spices',
    halfPakistaniChickenDesc: 'Half Pakistani chicken with rice and special spices',
    mathabiChickenDesc: 'Grilled mathabi chicken with rice',
    mathabiRibDesc: 'Mathabi lamb rib with rice',
    mathabiMeatDesc: 'Mathabi meat with rice',
    halfMathabiChickenDesc: 'Half mathabi chicken with rice',
    madfoonMeatDesc: 'Madfoon meat with rice',
    makboosMeatDesc: 'Makboos meat with rice',
    makboosChickenDesc: 'Makboos chicken with rice',
    halfMakboosChickenDesc: 'Half makboos chicken with rice',
    qoziShoulderDesc: 'Qozi lamb shoulder with rice',
    mandiShoulderQoziDesc: 'Mandi shoulder with qozi and rice',
    mandiShoulderQoziChickenDesc: 'Mandi shoulder with qozi, chicken, and rice',
    mandiRibChickenDesc: 'Mandi rib with chicken and rice',
    mandiChickenShoulderDesc: 'Mandi chicken with shoulder and rice',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChickenDesc: 'Combo of half mandi, mathabi, and madfoon chicken with rice',
    halfMandiChickenMandiMeatDesc: 'Half mandi chicken with mandi meat and rice',
    extraRiceDesc: 'Extra plate of rice',
    madfoonChickenDesc: 'Madfoon chicken with rice',
    appetizer1Desc: 'Appetizer 1 description',
    appetizer2Desc: 'Appetizer 2 description',
    appetizer3Desc: 'Appetizer 3 description',
    // Cart
    yourOrder: 'Your Order',
    total: 'Total',
    checkout: 'Checkout',
    // Checkout
    customerInfo: 'Customer Information',
    name: 'Name',
    phone: 'Phone Number',
    diningPreference: 'Dining Preference',
    insideRestaurant: 'Inside Restaurant',
    customLocation: 'Custom Location',
    branch: 'Branch',
    branch1: 'Koya Street Branch',
    branch2: 'Grand Majidi Mall Branch',
    tableNumber: 'Table Number',
    location: 'Location',
    submitOrder: 'Submit Order',
    // Languages
    arabic: 'العربية',
    english: 'English',
    kurdish: 'کوردی'
  },
  ku: {
    // Navigation
    home: 'سەرەتا',
    menu: 'مێنوو',
    cart: 'سبەت',
    // Homepage
    welcome: 'بەخێربێن بۆ',
    restaurantName: 'مەندی الحطاب',
    subtitle: 'بۆ خواردنی خۆشی کەنار دەریایی',
    orderNow: 'داوا بکە ئێستا',
    viewMenu: 'بینینی مێنوو',
    fastDelivery: 'گەیاندنی خێرا',
    freshIngredients: 'پێکهاتەی تازە',
    authenticTaste: 'تامێکی ڕەسەن',
    // Menu
    appetizers: 'پێشخۆری',
    mainCourses: 'خواردنە سەرەکییەکان',
    desserts: 'شیرینی',
    beverages: 'خواردنەوە',
    addToCart: 'زیادکردن بۆ سەبەتە',
    price: 'نرخ',
    chickenDishes: 'خواردنی مریشک',
    meatDishes: 'خواردنی گۆشت',
    // Food items
    mandiChicken: 'مەندی مریشک',
    mandiRibs: 'پەراسووی مەندی',
    mandiShoulder: 'شانی مەندی',
    mandiLamb: 'مەندی گۆشت',
    halfChicken: 'نیو مریشکی مەندی',
    qoziMeat: 'قۆزی گۆشت',
    hanithChicken: 'حەنیز مریشک',
    hanithShoulder: 'شانی حەنیز',
    hanithMeat: 'گۆشتی حەنیز',
    halfHanithChicken: 'نیو مریشکی حەنیز',
    pakistaniChicken: 'مریشکی پاکستانی',
    halfPakistaniChicken: 'نیو مریشکی پاکستانی',
    mathabiChicken: 'مریشکی مەثابی',
    mathabiRib: 'پەراسووی مەثابی',
    mathabiMeat: 'گۆشتی مەثابی',
    halfMathabiChicken: 'نیو مریشکی مەثابی',
    madfoonMeat: 'گۆشتی مەدفوون',
    makboosMeat: 'گۆشتی مەکبوس',
    makboosChicken: 'مریشکی مەکبوس',
    halfMakboosChicken: 'نیو مریشکی مەکبوس',
    qoziShoulder: 'شانی قۆزی',
    mandiShoulderQozi: 'شانی مەندی + قۆزی',
    mandiShoulderQoziChicken: 'شانی مەندی + قۆزی + مریشک',
    mandiRibChicken: 'پەراسووی مەندی + مریشک',
    mandiChickenShoulder: 'مەندی مریشک + شان',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChicken: 'نیو مەندی مریشک + نیو مەثابی مریشک + نیو مەدفوون مریشک',
    halfMandiChickenMandiMeat: 'نیو مەندی مریشک + گۆشتی مەندی',
    extraRice: 'برنجی زیادە',
    madfoonChicken: 'مریشکی مەدفوون',
    // Appetizers
    tabsi: 'تەبسی',
    tabsiDesc: 'تەبسی سەوزەوەری برژاو',
    fasoolia: 'فاسۆلیا',
    fasooliaDesc: 'فاسۆلیا لەگەڵ سۆسی تامدار',
    soup: 'شۆربا',
    soupDesc: 'شۆربای سەوزەوەر',
    jajik: 'جاجک',
    jajikDesc: 'سەلاطەی ئارەم بە خێوار',
    sahawk: 'سەحاوق',
    sahawkDesc: 'سەلاطەی تەماتە بە سیر',
    nuts: 'خواردنەوەری چەرەس',
    nutsDesc: 'خواردنەوەری چەرەسی هەمەجۆر',
    pickles: 'ترشی',
    picklesDesc: 'ترشی سەوزەوەر',
    yougurt: 'مەست',
    yougurtDesc: 'مەستی سادە',
    water: 'ئاو',
    waterDesc: 'ئاوی بەتاڵکراو',
    'soft drinks': 'خواردنەوەی گازی',
    'soft drinksDesc': 'خواردنەوەی گازی',
    // Descriptions
    mandiChickenDesc: 'مریشکی مەندی + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    mandiRibsDesc: 'پەراسووی مەڕ (١ کیلۆ) + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    mandiShoulderDesc: 'شانی مەڕ (١ کیلۆ) + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    mandiLambDesc: 'گۆشتی مەندی (نیوە کیلۆ) + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    halfChickenDesc: 'نیوەی مریشکی مەندی + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    qoziMeatDesc: 'قۆزی گۆشت (نیوە کیلۆ) + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    hanithChickenDesc: 'حەنیز مریشک + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    hanithShoulderDesc: 'حەنیز شان (١ کیلۆ) + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    hanithMeatDesc: 'نیوە کیلۆ حەنیز گۆشت + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    halfHanithChickenDesc: 'نیوەی حەنیز مریشک + تەشتی برنج + لۆبیا + حاجیک + سەحاوق + ترشی',
    pakistaniChickenDesc: 'مەندی پاکستانی بە برنج و چاشنی تایبەتی',
    halfPakistaniChickenDesc: 'نیوەی مەندی پاکستانی بە برنج و چاشنی تایبەتی',
    mathabiChickenDesc: 'مریشکی مەثابی برژاو لە سەر ئاگر بە برنج',
    mathabiRibDesc: 'پەراسووی مەثابی بە برنج',
    mathabiMeatDesc: 'گۆشتی مەثابی بە برنج',
    halfMathabiChickenDesc: 'نیوەی مریشکی مەثابی بە برنج',
    madfoonMeatDesc: 'گۆشتی مەدفوون بە برنج',
    makboosMeatDesc: 'گۆشتی مەکبوس بە برنج',
    makboosChickenDesc: 'مریشکی مەکبوس بە برنج',
    halfMakboosChickenDesc: 'نیوەی مریشکی مەکبوس بە برنج',
    qoziShoulderDesc: 'شانەی قۆزی بە برنج',
    mandiShoulderQoziDesc: 'شانەی مەندی بە قۆزی و برنج',
    mandiShoulderQoziChickenDesc: 'شانەی مەندی بە قۆزی، مریشک و برنج',
    mandiRibChickenDesc: 'پەراسووی مەندی بە مریشک و برنج',
    mandiChickenShoulderDesc: 'مەندی مریشک بە شان و برنج',
    halfMandiChickenHalfMathabiChickenHalfMadfoonChickenDesc: 'کۆمبۆی نیوەی مریشکی مەندی، مەثابی و مەدفوون بە برنج',
    halfMandiChickenMandiMeatDesc: 'نیوەی مریشکی مەندی بە گۆشتی مەندی و برنج',
    extraRiceDesc: 'قابەی برنجی زیادە',
    madfoonChickenDesc: 'مریشکی مەدفوون بە برنج',
    appetizer1: 'پێشخوان ١',
    appetizer1Desc: 'وەسفی پێشخوان ١',
    appetizer2: 'پێشخوان ٢',
    appetizer2Desc: 'وەسفی پێشخوان ٢',
    appetizer3: 'پێشخوان ٣',
    appetizer3Desc: 'وەسفی پێشخوان ٣',
    // Cart
    yourOrder: 'داواکارییەکەت',
    total: 'کۆی گشتی',
    checkout: 'تەواوکردنی داواکاری',
    // Checkout
    customerInfo: 'زانیاری کڕیار',
    name: 'ناو',
    phone: 'ژمارەی تەلەفۆن',
    diningPreference: 'ترجیحی خواردن',
    insideRestaurant: 'لە ناو چێشتخانە',
    customLocation: 'شوێنی تایبەت',
    branch: 'لق',
    branch1: 'لقی شەقامی کۆیە',
    branch2: 'لقی گراند ماجیدی مۆڵ',
    tableNumber: 'ژمارەی مێز',
    location: 'شوێن',
    submitOrder: 'ناردنی داواکاری',
    // Languages
    arabic: 'عەرەبی',
    english: 'ئینگلیزی',
    kurdish: 'کوردی'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
